### ISSUE TITLE
Support for inserting data over streaming inserts

### ISSUE THREAD

**Issue by jags9415** [embulk/embulk-output-bigquery#111]
Hello! 

I was wondering if supporting streaming inserts is a planned feature or the plugin is meant to work only with load operations? 

I see in the README the suggestion of using the Fluentd plugin, but I was looking for a way of using streaming inserts directly with an embulk output plugin?

**Comment by sakama** [comment]
Hello.

Speaking about this plugin, the answer is no.
Not only this plugin but also Embulk core itself isn't intended to run with waiting for data as a daemon.
Embulk process starts on JVM when `embulk (guess|preview|run)` commands are called, terminates when the bulk load process ends.

But speaking only about output plugin, it might be possible to use streaming inserts with [embulk-output-fluentd](https://github.com/smdmts/embulk-output-fluentd) and [fluent-plugin-bigquery](https://github.com/kaizenplatform/fluent-plugin-bigquery). I had never tried this combination, though.

**Comment by jags9415** [comment]
Thanks for the answer @sakama, that makes sense.

I'm closing this issue since it was more a question than an issue.
