### ISSUE TITLE
TRUNCATE  TABLE when import newer data

### ISSUE THREAD

**Issue by shibacow** [embulk/embulk-output-bigquery#12]
I'd like to trancate table when newer data using embulk-output-bigquey.

load job have parameter configuration.load.writeDisposition WRITE_TRUNCATE.
https://cloud.google.com/bigquery/docs/reference/v2/jobs#resource

this parameter is enable in this plugin?

**Comment by sakama** [comment]
Sorry, writeDisposition parameter is not supported, and I think it's difficult.

Embulk can execute multiple tasks at the same time.
In this case, embulk-output-bigquery should insert task as BigQuery's job like below.

task01 **WRITE_TRUNCATE** (maybe job will complete first)
task00 WRITE_APPEND
task02 WRITE_APPEND
task03 WRITE_APPEND

But plugin can't know which job will complete first.

**Comment by shibacow** [comment]
Oh, I see.
Thanks your reply.
