### ISSUE TITLE
faraday-net_http requires Ruby version >= 2.4.0.

### ISSUE THREAD

**Issue by bagavathy-priya-4742** [embulk/embulk-output-bigquery#131]
![Screenshot 2021-04-19 at 5 01 24 PM](https://user-images.githubusercontent.com/82817984/115237838-a72f4480-a13a-11eb-86ab-26b2ad6c0107.png)
While installing embulk-output-bigquery, the following error is coming 
"ERROR:  Error installing embulk-output-bigquery:
	There are no versions of faraday-net_http (~> 1.0) compatible with your Ruby & RubyGems. Maybe try installing an older version of the gem you're looking for?
	faraday-net_http requires Ruby version >= 2.4.0. The current ruby version is 2.3.0."

But while running the command ruby -v 
It gives "ruby 2.4.10p364 (2020-03-31 revision 67879) [x86_64-linux]"

Kindly put some light into this issue and try to fix it as soon as possible.

**Comment by hiroyuki-sato** [comment]
Hello, @Bagavathyshopf 
Thank you for creating this report.

Could you try the following until fix?

```
embulk gem install representable -v 3.0.4
embulk gem install faraday -v 0.17.4
embulk gem install embulk-output-bigquery
```

**Comment by bagavathy-priya-4742** [comment]
Hi,

It solved the problem. Thanks for the prompt response.

Regards,
Bagavathy Priya N
