### ISSUE TITLE
Error: Bad character (ASCII 0) encountered.

### ISSUE THREAD

**Issue by bagavathy-priya-4742** [embulk/embulk-output-bigquery#132]
While loading the data to embulk bigquery, the following error is showing up
"Caused by: org.jruby.exceptions.RaiseException: (Error) failed during waiting a Load job, get_job(bagavathy-embulk, embulk_load_job_d5ff4495-1921-4e15-8e1d-bcdec541cfa5), errors:[{:reason=>"invalid", :message=>"Error while reading data, error message: Error detected while parsing row starting at position: 46994450. Error: Bad character (ASCII 0) encountered."},"

I used encoding:UTF-8 in the out section of the yml config file.
I tried with various other encoding options like 'utf-16', 'ISO-8859-1', and it doesn't solve the problem. Kindly help to solve this issue. 
![Screenshot 2021-04-22 at 9 31 59 AM](https://user-images.githubusercontent.com/82817984/115653884-a4f10400-a34d-11eb-86ea-df8b607170e7.png)

**Comment by hiroyuki-sato** [comment]
Hello, @Bagavathyshopf 
If you use CSV format, could you try JSON format?
https://github.com/embulk/embulk-output-bigquery#formatter-performance-issue

**Comment by hiroyuki-sato** [comment]
I close this issue but feel free to reopen if you need.
