### ISSUE TITLE
multipart-post requires Ruby version >= 2.6.0

### ISSUE THREAD

**Issue by RNm-dove** [embulk/embulk-output-bigquery#144]
I use embulk-0.9.24.

When I was installing embulk-output-biqquery v0.6.7, this error appeared. 

```
ERROR:  Error installing embulk-output-bigquery:
multipart-post requires Ruby version >= 2.6.0.
```

This error was fixed by installing `multipart-post -v 2.1.1`,  but nest error raised.

```
ERROR:  Error installing embulk-output-bigquery:
jwt requires Ruby version >= 2.5.0.
``` 

This error was also fixed by installing  `jwt v2.3.0`.  [Ruby jwt gem of v2.4.0 or newer dropped support ruby v2.5.0 or older](https://github.com/jwt/ruby-jwt/releases). 

So these gem may need version lock when using with `embulk-0.9.24`

```
embulk gem install multipart-post -v 2.1.1
embulk gem install jwt -v 2.3.0
```

**Comment by yuanchieh-at** [comment]
I encountered the same questions. It solved my problem. thanks
It would be better if repo could lock these gem version.

**Comment by hiroyuki-sato** [comment]
embulk-output-bigquery v0.7 supports Ruby 2.7(JRuby 9.3.x) and later. Please try it.
