### ISSUE TITLE
job fail when there's Korean in json

### ISSUE THREAD

**Issue by MarkVuclip** [embulk/embulk-output-bigquery#62]
Hi 
     We use Embulk v0.8.13
     plugin embulk-input-redshift (0.7.4)
     plugin embulk-output-bigquery (0.4.2)

job failed when there's Korean in json
Error: org.jruby.exceptions.RaiseException: (Error) failed during waiting a Load job, get_job(vuclipdataflow-1301, embulk_load_job_bc325bd0-6b78-4ca9-954a-7915dbe4cc55), errors:[{:reason=>"invalid", :message=>"Too many errors encountered."}, {:reason=>"invalid", :location=>"/gzip/subrange/file-00000000", :message=>"CSV table references column position 20, but line starting at position:22635868 contains only 20 columns."}]

{"user_geo":"10","user_ccode":"ID",,"user_name":"신제군","acq_campaign":"Viu_ID_TKM"}
All this info should in a column,but becuase of the Korean,the end part： "acq_campaign":"Viu_ID_TKM"
will be split to a new column in the tmp csv,then cause the exception above.

how to fix it?Pls help.

**Comment by sonots** [comment]
Is it JSON or CSV? It is not valid in both.
It looks you are trying to insert as a CSV?

**Comment by sonots** [comment]
No response. Let me close.
