### ISSUE TITLE
GCS Bulk into BigQuery Partitioned Tables

### ISSUE THREAD

**Issue by flashtraderpro** [embulk/embulk-output-bigquery#67]
Hi,
I have several CSV files in GCS bucket. Each file has a name like this:

PETR4_2017-03-10.csv
PETR4_2017-03-11.csv
PETR4_XXXXXXXXX.csv

Each one of them represent data for one day and I need to insert them into partitioned tables at once. I wonder if that is possible with embulk since BG has a 50.000 job quota.

Thanks.

**Comment by sonots** [comment]
In my understanding, a job is required to load data into a partition because a partition decorator must be specified. Thus, it is not possible with current google API itself.

**Comment by flashtraderpro** [comment]
Then I need to run on job for each table?

Thanks.



*Fernando Freitas*
Onesoft Tecnologia S.A. | Tecnologia
(11) 3080-2061 | flashtrader.com.br


* São Paulo | SP*
Av. Brigadeiro Faria Lima,
3311 | 4° andar
CEP: 04538-132



*Importante:*
Esta mensagem, incluindo os seus anexos, contém informações confidenciais
destinadas a indivíduo e propósito específicos, sendo protegida por lei.
Caso você não seja a pessoa a quem foi dirigida a mensagem, deve apagá-la.
É terminantemente proibida a utilização, acesso, cópia ou divulgação não
autorizada das informações presentes nesta mensagem. As informações
contidas nesta mensagem e em seus anexos são de responsabilidade de seu
autor, não representando necessariamente idéias, opiniões, pensamentos ou
qualquer forma de posicionamento por parte da Onesoft Tecnologia S.A.
O investimento em ações é um investimento de risco e rentabilidade passada
não é garantia de rentabilidade futura. Na realização de operações com
derivativos existe a possibilidade de perdas superiores aos valores
investidos, podendo resultar em significativas perdas patrimoniais.

2017-04-04 8:35 GMT-03:00 Naotoshi Seo <notifications@github.com>:

**Comment by sonots** [comment]
each partition, correctly
