### ISSUE TITLE
Improvement of file transfer rate

### ISSUE THREAD

**Issue by sakama** [embulk/embulk-output-bigquery#7]
File transfer rate is slow besides from GCE instances.
- from GCE instance 25MB/sec
- other environment 3〜7MB/sec

But gsutil can upload 50MB/sec from low low-speed line like my home.
## Problems
- Google APIs Client Library for Java doesn't support multipart upload.
- I think it's too difficult to implove high upload throughput only using multipart upload.

**Comment by sonots** [comment]
Fixed via https://github.com/embulk/embulk-output-bigquery/pull/35. We now support parallel uploads. Let me close. 

BTW, [mutlipart upload of BigQuery](https://cloud.google.com/bigquery/loading-data-post-request#multipart) just means to reduce one HTTP request by sending configuration JSON and body data together. 

The big time consuming point of BigQuery loading is waiting to finish LOAD job. Reducing one HTTP request to send configuration JSON does not improve performance much (theoretically, and based under my experiment).
