### ISSUE TITLE
Error permission denied  when install embulk-output-bigquery

### ISSUE THREAD

**Issue by ThaiCo60** [embulk/embulk-output-bigquery#80]
[Sorry if my English is not good]

i have try in windows: embulk gem install embulk-output-bigquery
and i get an error: Error while executing gem
permission denied - File.syslink

looks when being executing gem, File.symlink copyed somewhere that I do not have permission and I do not know where it is

I tried to fix the problem but not resolved, please help me about that

**Comment by sakama** [comment]
Hi.

Could you try `gem install embulk-output-bigquery --verbose` to check install path?
Although I'm not familiar with using Embulk with Windows environment, I guess changing permission of  parent directory that failed to create symlink under child directory might solve this problem.

```sh
...
GET https://api.rubygems.org/gems/embulk-output-bigquery-0.4.7.gem
Fetching: embulk-output-bigquery-0.4.7.gem (100%)
200 OK
/Users/sakama/.rbenv/versions/jruby-9.1.5.0/gemsets/test/gems/embulk-output-bigquery-0.4.7/.gitignore
...
```
I use macOS Sierra and rbenv to manage Ruby application. It should have pretty different path from your env.

**Comment by ThaiCo60** [comment]
Thank @sakama 

I installed the lower version: embulk gem install embulk-output-bigquery -v 0.4.0
and it works for me.
